syntax = "proto3";

package auth.v1;

option go_package = "github.com/Khansa01/collaboration-app/be/internal/gen/auth/v1;authv1";

message RegisterRequest {
  string name = 1;
  string email = 2;
  string password = 3;
}

message RegisterResponse {
  string message = 1;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  string token = 1;
  string name = 2;
  string email = 3;
}

service AuthService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
}