// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file collaboration.proto (package collaboration.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file collaboration.proto.
 */
export const file_collaboration: GenFile = /*@__PURE__*/
  fileDesc("ChNjb2xsYWJvcmF0aW9uLnByb3RvEhBjb2xsYWJvcmF0aW9uLnYxIl8KCU9wZXJhdGlvbhIOCgZkb2NfaWQYASABKAkSDwoHdXNlcl9pZBgCIAEoCRIPCgdvcF90eXBlGAMgASgJEg8KB3BheWxvYWQYBCABKAwSDwoHdmVyc2lvbhgFIAEoAyI1ChFPcGVyYXRpb25SZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEg8KB3ZlcnNpb24YAiABKAMybAoUQ29sbGFib3JhdGlvblNlcnZpY2USVAoMU3luY0RvY3VtZW50EhsuY29sbGFib3JhdGlvbi52MS5PcGVyYXRpb24aIy5jb2xsYWJvcmF0aW9uLnYxLk9wZXJhdGlvblJlc3BvbnNlKAEwAUJYWlZnaXRodWIuY29tL0toYW5zYTAxL2NvbGxhYm9yYXRpb24tYXBwL2JlL2ludGVybmFsL2dlbi9jb2xsYWJvcmF0aW9uL3YxO2NvbGxhYm9yYXRpb252MWIGcHJvdG8z");

/**
 * @generated from message collaboration.v1.Operation
 */
export type Operation = Message<"collaboration.v1.Operation"> & {
  /**
   * @generated from field: string doc_id = 1;
   */
  docId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string op_type = 3;
   */
  opType: string;

  /**
   * @generated from field: bytes payload = 4;
   */
  payload: Uint8Array;

  /**
   * @generated from field: int64 version = 5;
   */
  version: bigint;
};

/**
 * Describes the message collaboration.v1.Operation.
 * Use `create(OperationSchema)` to create a new message.
 */
export const OperationSchema: GenMessage<Operation> = /*@__PURE__*/
  messageDesc(file_collaboration, 0);

/**
 * @generated from message collaboration.v1.OperationResponse
 */
export type OperationResponse = Message<"collaboration.v1.OperationResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: int64 version = 2;
   */
  version: bigint;
};

/**
 * Describes the message collaboration.v1.OperationResponse.
 * Use `create(OperationResponseSchema)` to create a new message.
 */
export const OperationResponseSchema: GenMessage<OperationResponse> = /*@__PURE__*/
  messageDesc(file_collaboration, 1);

/**
 * @generated from service collaboration.v1.CollaborationService
 */
export const CollaborationService: GenService<{
  /**
   * @generated from rpc collaboration.v1.CollaborationService.SyncDocument
   */
  syncDocument: {
    methodKind: "bidi_streaming";
    input: typeof OperationSchema;
    output: typeof OperationResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_collaboration, 0);

