// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file collaboration.proto (package collaboration.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Operation, OperationResponse } from "./collaboration_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service collaboration.v1.CollaborationService
 */
export const CollaborationService = {
  typeName: "collaboration.v1.CollaborationService",
  methods: {
    /**
     * @generated from rpc collaboration.v1.CollaborationService.SyncDocument
     */
    syncDocument: {
      name: "SyncDocument",
      I: Operation,
      O: OperationResponse,
      kind: MethodKind.BiDiStreaming,
    },
  }
} as const;

