// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file document.proto (package document.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateDocumentRequest, CreateDocumentResponse, GetDocumentRequest, GetDocumentResponse, ListDocumentsRequest, ListDocumentsResponse } from "./document_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service document.v1.DocumentService
 */
export const DocumentService = {
  typeName: "document.v1.DocumentService",
  methods: {
    /**
     * @generated from rpc document.v1.DocumentService.CreateDocument
     */
    createDocument: {
      name: "CreateDocument",
      I: CreateDocumentRequest,
      O: CreateDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc document.v1.DocumentService.GetDocument
     */
    getDocument: {
      name: "GetDocument",
      I: GetDocumentRequest,
      O: GetDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc document.v1.DocumentService.ListDocuments
     */
    listDocuments: {
      name: "ListDocuments",
      I: ListDocumentsRequest,
      O: ListDocumentsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

