// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file document.proto (package document.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file document.proto.
 */
export const file_document: GenFile = /*@__PURE__*/
  fileDesc("Cg5kb2N1bWVudC5wcm90bxILZG9jdW1lbnQudjEiqAEKCERvY3VtZW50EgoKAmlkGAEgASgJEg0KBXRpdGxlGAIgASgJEg8KB2NvbnRlbnQYAyABKAkSEAoIb3duZXJfaWQYBCABKAkSLgoKY3JlYXRlZF9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiJgoVQ3JlYXRlRG9jdW1lbnRSZXF1ZXN0Eg0KBXRpdGxlGAEgASgJIkEKFkNyZWF0ZURvY3VtZW50UmVzcG9uc2USJwoIZG9jdW1lbnQYASABKAsyFS5kb2N1bWVudC52MS5Eb2N1bWVudCIgChJHZXREb2N1bWVudFJlcXVlc3QSCgoCaWQYASABKAkiPgoTR2V0RG9jdW1lbnRSZXNwb25zZRInCghkb2N1bWVudBgBIAEoCzIVLmRvY3VtZW50LnYxLkRvY3VtZW50IhYKFExpc3REb2N1bWVudHNSZXF1ZXN0IkEKFUxpc3REb2N1bWVudHNSZXNwb25zZRIoCglkb2N1bWVudHMYASADKAsyFS5kb2N1bWVudC52MS5Eb2N1bWVudCI0ChVVcGRhdGVEb2N1bWVudFJlcXVlc3QSCgoCaWQYASABKAkSDwoHY29udGVudBgCIAEoCSJBChZVcGRhdGVEb2N1bWVudFJlc3BvbnNlEicKCGRvY3VtZW50GAEgASgLMhUuZG9jdW1lbnQudjEuRG9jdW1lbnQy8QIKD0RvY3VtZW50U2VydmljZRJZCg5DcmVhdGVEb2N1bWVudBIiLmRvY3VtZW50LnYxLkNyZWF0ZURvY3VtZW50UmVxdWVzdBojLmRvY3VtZW50LnYxLkNyZWF0ZURvY3VtZW50UmVzcG9uc2USUAoLR2V0RG9jdW1lbnQSHy5kb2N1bWVudC52MS5HZXREb2N1bWVudFJlcXVlc3QaIC5kb2N1bWVudC52MS5HZXREb2N1bWVudFJlc3BvbnNlElYKDUxpc3REb2N1bWVudHMSIS5kb2N1bWVudC52MS5MaXN0RG9jdW1lbnRzUmVxdWVzdBoiLmRvY3VtZW50LnYxLkxpc3REb2N1bWVudHNSZXNwb25zZRJZCg5VcGRhdGVEb2N1bWVudBIiLmRvY3VtZW50LnYxLlVwZGF0ZURvY3VtZW50UmVxdWVzdBojLmRvY3VtZW50LnYxLlVwZGF0ZURvY3VtZW50UmVzcG9uc2VCTlpMZ2l0aHViLmNvbS9LaGFuc2EwMS9jb2xsYWJvcmF0aW9uLWFwcC9iZS9pbnRlcm5hbC9nZW4vZG9jdW1lbnQvdjE7ZG9jdW1lbnR2MWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message document.v1.Document
 */
export type Document = Message<"document.v1.Document"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * @generated from field: string owner_id = 4;
   */
  ownerId: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 6;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message document.v1.Document.
 * Use `create(DocumentSchema)` to create a new message.
 */
export const DocumentSchema: GenMessage<Document> = /*@__PURE__*/
  messageDesc(file_document, 0);

/**
 * @generated from message document.v1.CreateDocumentRequest
 */
export type CreateDocumentRequest = Message<"document.v1.CreateDocumentRequest"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;
};

/**
 * Describes the message document.v1.CreateDocumentRequest.
 * Use `create(CreateDocumentRequestSchema)` to create a new message.
 */
export const CreateDocumentRequestSchema: GenMessage<CreateDocumentRequest> = /*@__PURE__*/
  messageDesc(file_document, 1);

/**
 * @generated from message document.v1.CreateDocumentResponse
 */
export type CreateDocumentResponse = Message<"document.v1.CreateDocumentResponse"> & {
  /**
   * @generated from field: document.v1.Document document = 1;
   */
  document?: Document | undefined;
};

/**
 * Describes the message document.v1.CreateDocumentResponse.
 * Use `create(CreateDocumentResponseSchema)` to create a new message.
 */
export const CreateDocumentResponseSchema: GenMessage<CreateDocumentResponse> = /*@__PURE__*/
  messageDesc(file_document, 2);

/**
 * @generated from message document.v1.GetDocumentRequest
 */
export type GetDocumentRequest = Message<"document.v1.GetDocumentRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message document.v1.GetDocumentRequest.
 * Use `create(GetDocumentRequestSchema)` to create a new message.
 */
export const GetDocumentRequestSchema: GenMessage<GetDocumentRequest> = /*@__PURE__*/
  messageDesc(file_document, 3);

/**
 * @generated from message document.v1.GetDocumentResponse
 */
export type GetDocumentResponse = Message<"document.v1.GetDocumentResponse"> & {
  /**
   * @generated from field: document.v1.Document document = 1;
   */
  document?: Document | undefined;
};

/**
 * Describes the message document.v1.GetDocumentResponse.
 * Use `create(GetDocumentResponseSchema)` to create a new message.
 */
export const GetDocumentResponseSchema: GenMessage<GetDocumentResponse> = /*@__PURE__*/
  messageDesc(file_document, 4);

/**
 * @generated from message document.v1.ListDocumentsRequest
 */
export type ListDocumentsRequest = Message<"document.v1.ListDocumentsRequest"> & {
};

/**
 * Describes the message document.v1.ListDocumentsRequest.
 * Use `create(ListDocumentsRequestSchema)` to create a new message.
 */
export const ListDocumentsRequestSchema: GenMessage<ListDocumentsRequest> = /*@__PURE__*/
  messageDesc(file_document, 5);

/**
 * @generated from message document.v1.ListDocumentsResponse
 */
export type ListDocumentsResponse = Message<"document.v1.ListDocumentsResponse"> & {
  /**
   * @generated from field: repeated document.v1.Document documents = 1;
   */
  documents: Document[];
};

/**
 * Describes the message document.v1.ListDocumentsResponse.
 * Use `create(ListDocumentsResponseSchema)` to create a new message.
 */
export const ListDocumentsResponseSchema: GenMessage<ListDocumentsResponse> = /*@__PURE__*/
  messageDesc(file_document, 6);

/**
 * @generated from message document.v1.UpdateDocumentRequest
 */
export type UpdateDocumentRequest = Message<"document.v1.UpdateDocumentRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string content = 2;
   */
  content: string;
};

/**
 * Describes the message document.v1.UpdateDocumentRequest.
 * Use `create(UpdateDocumentRequestSchema)` to create a new message.
 */
export const UpdateDocumentRequestSchema: GenMessage<UpdateDocumentRequest> = /*@__PURE__*/
  messageDesc(file_document, 7);

/**
 * @generated from message document.v1.UpdateDocumentResponse
 */
export type UpdateDocumentResponse = Message<"document.v1.UpdateDocumentResponse"> & {
  /**
   * @generated from field: document.v1.Document document = 1;
   */
  document?: Document | undefined;
};

/**
 * Describes the message document.v1.UpdateDocumentResponse.
 * Use `create(UpdateDocumentResponseSchema)` to create a new message.
 */
export const UpdateDocumentResponseSchema: GenMessage<UpdateDocumentResponse> = /*@__PURE__*/
  messageDesc(file_document, 8);

/**
 * @generated from service document.v1.DocumentService
 */
export const DocumentService: GenService<{
  /**
   * @generated from rpc document.v1.DocumentService.CreateDocument
   */
  createDocument: {
    methodKind: "unary";
    input: typeof CreateDocumentRequestSchema;
    output: typeof CreateDocumentResponseSchema;
  },
  /**
   * @generated from rpc document.v1.DocumentService.GetDocument
   */
  getDocument: {
    methodKind: "unary";
    input: typeof GetDocumentRequestSchema;
    output: typeof GetDocumentResponseSchema;
  },
  /**
   * @generated from rpc document.v1.DocumentService.ListDocuments
   */
  listDocuments: {
    methodKind: "unary";
    input: typeof ListDocumentsRequestSchema;
    output: typeof ListDocumentsResponseSchema;
  },
  /**
   * @generated from rpc document.v1.DocumentService.UpdateDocument
   */
  updateDocument: {
    methodKind: "unary";
    input: typeof UpdateDocumentRequestSchema;
    output: typeof UpdateDocumentResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_document, 0);

