// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file presence.proto (package presence.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file presence.proto.
 */
export const file_presence: GenFile = /*@__PURE__*/
  fileDesc("Cg5wcmVzZW5jZS5wcm90bxILcHJlc2VuY2UudjEifQoMVXNlclByZXNlbmNlEg8KB3VzZXJfaWQYASABKAkSDgoGZG9jX2lkGAIgASgJEgwKBG5hbWUYAyABKAkSEQoJaXNfb25saW5lGAQgASgIEisKBmN1cnNvchgFIAEoCzIbLnByZXNlbmNlLnYxLkN1cnNvclBvc2l0aW9uIi8KDkN1cnNvclBvc2l0aW9uEg0KBWluZGV4GAEgASgFEg4KBmxlbmd0aBgCIAEoBSJOCg9QcmVzZW5jZVJlcXVlc3QSDgoGZG9jX2lkGAEgASgJEisKCHByZXNlbmNlGAIgASgLMhkucHJlc2VuY2UudjEuVXNlclByZXNlbmNlIjwKEFByZXNlbmNlUmVzcG9uc2USKAoFdXNlcnMYASADKAsyGS5wcmVzZW5jZS52MS5Vc2VyUHJlc2VuY2UyYgoPUHJlc2VuY2VTZXJ2aWNlEk8KDFN5bmNQcmVzZW5jZRIcLnByZXNlbmNlLnYxLlByZXNlbmNlUmVxdWVzdBodLnByZXNlbmNlLnYxLlByZXNlbmNlUmVzcG9uc2UoATABQk5aTGdpdGh1Yi5jb20vS2hhbnNhMDEvY29sbGFib3JhdGlvbi1hcHAvYmUvaW50ZXJuYWwvZ2VuL3ByZXNlbmNlL3YxO3ByZXNlbmNldjFiBnByb3RvMw");

/**
 * @generated from message presence.v1.UserPresence
 */
export type UserPresence = Message<"presence.v1.UserPresence"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string doc_id = 2;
   */
  docId: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: bool is_online = 4;
   */
  isOnline: boolean;

  /**
   * @generated from field: presence.v1.CursorPosition cursor = 5;
   */
  cursor?: CursorPosition | undefined;
};

/**
 * Describes the message presence.v1.UserPresence.
 * Use `create(UserPresenceSchema)` to create a new message.
 */
export const UserPresenceSchema: GenMessage<UserPresence> = /*@__PURE__*/
  messageDesc(file_presence, 0);

/**
 * @generated from message presence.v1.CursorPosition
 */
export type CursorPosition = Message<"presence.v1.CursorPosition"> & {
  /**
   * @generated from field: int32 index = 1;
   */
  index: number;

  /**
   * @generated from field: int32 length = 2;
   */
  length: number;
};

/**
 * Describes the message presence.v1.CursorPosition.
 * Use `create(CursorPositionSchema)` to create a new message.
 */
export const CursorPositionSchema: GenMessage<CursorPosition> = /*@__PURE__*/
  messageDesc(file_presence, 1);

/**
 * @generated from message presence.v1.PresenceRequest
 */
export type PresenceRequest = Message<"presence.v1.PresenceRequest"> & {
  /**
   * @generated from field: string doc_id = 1;
   */
  docId: string;

  /**
   * @generated from field: presence.v1.UserPresence presence = 2;
   */
  presence?: UserPresence | undefined;
};

/**
 * Describes the message presence.v1.PresenceRequest.
 * Use `create(PresenceRequestSchema)` to create a new message.
 */
export const PresenceRequestSchema: GenMessage<PresenceRequest> = /*@__PURE__*/
  messageDesc(file_presence, 2);

/**
 * @generated from message presence.v1.PresenceResponse
 */
export type PresenceResponse = Message<"presence.v1.PresenceResponse"> & {
  /**
   * @generated from field: repeated presence.v1.UserPresence users = 1;
   */
  users: UserPresence[];
};

/**
 * Describes the message presence.v1.PresenceResponse.
 * Use `create(PresenceResponseSchema)` to create a new message.
 */
export const PresenceResponseSchema: GenMessage<PresenceResponse> = /*@__PURE__*/
  messageDesc(file_presence, 3);

/**
 * @generated from service presence.v1.PresenceService
 */
export const PresenceService: GenService<{
  /**
   * @generated from rpc presence.v1.PresenceService.SyncPresence
   */
  syncPresence: {
    methodKind: "bidi_streaming";
    input: typeof PresenceRequestSchema;
    output: typeof PresenceResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_presence, 0);

