// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file presence.proto (package presence.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PresenceRequest, PresenceResponse } from "./presence_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service presence.v1.PresenceService
 */
export const PresenceService = {
  typeName: "presence.v1.PresenceService",
  methods: {
    /**
     * @generated from rpc presence.v1.PresenceService.SyncPresence
     */
    syncPresence: {
      name: "SyncPresence",
      I: PresenceRequest,
      O: PresenceResponse,
      kind: MethodKind.BiDiStreaming,
    },
  }
} as const;

